packages/native_pdf_renderer/ios/Classes/Hooks.swift
packages/native_pdf_renderer/ios/Classes/document/Page.swift

For iOS the backgroundColor was not correctly used for filling the rendered image.
The pull request changes the logic of preparing de Data and fill the background of the image using the correct color passed in backgroundColor parameter.

[native_pdf_renderer] FIXed backgroundColor fill for iOS

---

packages/native_pdf_renderer/android/build.gradle

This resolves an issue with flutter version 1.12 while building apks by updating compileSdkVersion to 28.
The issue is described here: https://github.com/flutter/flutter/issues/46881#issuecomment-565174872

Resolve issue with building an apk file on flutter 1.12

---

packages/native_pdf_renderer/example/ios/Flutter/Flutter.podspec
packages/native_pdf_renderer/example/ios/Runner.xcodeproj/project.pbxproj
packages/native_pdf_renderer/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/native_pdf_renderer/example/lib/main.dart
packages/native_pdf_renderer/example/pubspec.yaml
packages/native_pdf_renderer/lib/src/document.dart
packages/native_pdf_renderer/lib/src/page.dart
packages/native_pdf_renderer/lib/src/page_image.dart
packages/native_pdf_renderer/lib/src/web/document/document.dart
packages/native_pdf_renderer/lib/src/web/document/page.dart
packages/native_pdf_renderer/lib/src/web/native_pdf_renderer_plugin.dart
packages/native_pdf_renderer/lib/src/web/pdfjs.dart
packages/native_pdf_renderer/lib/src/web/resources/document_repository.dart
packages/native_pdf_renderer/lib/src/web/resources/page_repository.dart
packages/native_pdf_renderer/lib/src/web/resources/repository.dart
packages/native_pdf_renderer/pubspec.lock
packages/native_pdf_renderer/pubspec.yaml
packages/native_pdf_renderer/test/native_pdf_renderer_test.dart

With the release of Flutter 2, I updated the dependencies for the native_pdf_renderer to the latest versions that support null safety and then ran the `dart migrate` tool to migrate the code base. The same methodology was applied to the `example` project.
This is in support of #147

Support for sound null safety via the dart migration tool.

---

packages/native_pdf_renderer/lib/src/document.dart

When rendering pdf docs from a Uint8List, the list was also being unnecessarily converted into a string. This removes that extra conversion to improve performance and save RAM.

[native_pdf_renderer] Avoided unnecessary memory usage

---

packages/auto_animated/lib/src/animate_if_visible.dart

Fixes the issue on flutter web, that elements that are not visible and whose animation has not been reversed, stay visible when returning back to being visible when reAnimateOnVisibility is set to true

Fixes issue in flutter web when reAnimateOnVisibility is set to true

---

packages/explorer/example/lib/main.dart
packages/explorer/lib/src/i18n/localization_delegate.dart
packages/explorer/lib/src/i18n/messages/messages_all.dart
packages/explorer/lib/src/i18n/messages/messages_fr.dart
packages/explorer/locales/intl_message_fr.arb

fix : `Unhandled Exception: type '() => Future<dynamic>' is not a subtype of type '() => Future<Object>' in type cast`
The explorer pluggin does not work. At least under  (I haven't tried an older version) : 
```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (il y a 11 jours) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```
A cast error is caused by : `localizationsDelegates: [ExplorerLocalizationsDelegate()]`
I did a quick fix by removing the forced cast to let the dynamic conversion do it.
I know that this code has been generated via `package:intl/generate_localized.dart` but at least now it works.

cast error while ExplorerLocalizationsDelegate() + french support

---

packages/native_pdf_view/pubspec.lock
packages/native_pdf_view/pubspec.yaml

An issue was fixed in the `photo_view` dependency that made it impossible to use with the newest flutter version (2.3, currently in beta). Bumping the dependency here as well.
See https://github.com/fireslime/photo_view/issues/441 for more information
Do I need to update the changelog myself or can you do it when you create a release?

Update photo_view dependency to 0.12.0

---

packages/native_pdf_view/pubspec.yaml

This fixes #202 by updating `photo_view`. I tested the PDF view on both iOS and Android devices with Flutter 2.5.0-1.0.pre (channel dev).

Fix for [BUG] 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'

---

packages/native_pdf_view/lib/src/native_pdf_view.dart

When going back from page having `PdfView()` widget, `null check operator used on a null value` exception is thrown by package. It may be caused by `PdfDocument` gets destroyed before view.
The example with this issue can be reproduced by below:
```dart
class PdfViewPage extends StatelessWidget {
const PdfViewPage({Key? key, required this.title, required this.pdfUrl})
: super(key: key);
final String title;
final String pdfUrl;
@override
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: Text(title),
),
body: Consumer(builder: (context, watch, child) {
final pdfPathAsync = watch(invoicePdfStateProvider(pdfUrl));
return pdfPathAsync.when(
data: (pdfPath) {
final pdfController = PdfController(
document: PdfDocument.openFile(pdfPath),
);
return Center(
child: …
```

Fixed null check operator used on a null value when closing PdfView widget.

---

packages/native_pdf_renderer/README.md
packages/native_pdf_renderer/windows/CMakeLists.txt

* Updates the pdfium version used to the latest stable chromium version
* Provides a mechanism for apps to override this version with a different version
This only affects Windows

Bump pdfium version and allow host app to overwrite version used

---

packages/pdfx/lib/pdfx.dart

When the command `flutter pub get` is executed, the resulting file `generated_plugin_registrant.dart` generates an incorrect import with the following warning `Don't import implementation files from another package`. This would be resolved.

Added pdfx_plugin.dart into exports list

---

packages/pdfx/android/build.gradle

Using `mavenCentral` instead of `jcenter` in `repositories` to remove the dependency on `jcenter` which often has downtime. 
Only did this for `pdfx` but can do this for others if desired.

swap jcenter for mavenCentral

---

packages/pdfx/CHANGELOG.md
packages/pdfx/example/pubspec.yaml
packages/pdfx/pubspec.yaml

The example was already overriding this dependency to point to master which is 0.14.0.  I'm using another package flutter_quill which also depends on photo_view and was recently updated to 0.14.0.
There are no breaking changes between 0.13.0 and 0.14.0 of photo_view

pdfx - Update photo_view dependency to 0.14.0

---

packages/pdfx/README.md

Seems that the local type had been renamed, but the README was not yet adapted.

Fix render `format` example in README

---

packages/epub_view/lib/src/ui/epub_view.dart

This pr is adding an optional `shrinkWrap` parameter to `ScrollablePositionedList.builder`;
**Motivation.**
I'm using `Epub` inside `CustomScrollView`, which has its own scroll. The current version of epub viewer, doesn't have shrinkWrap parameter inside the  ScrollablePositionedList.builder. Wich gives ScrollablePositionedList  expand to the maximum allowed height. CustomScrollView has unbounded constraints. That gives me  `Vertical viewport was given unbounded height.` exception.
**Change**
- Added optional named `shrinkWrap` parameter to `EpubView` with `false` default value;

[epub-view] add optional shrinkWrap parameter to ScrollablePositionedList.builder

---

packages/pdfx/pubspec.yaml

Hey guys,
could you use the newer version of device_info_plus? Checking it locally with pub outdated showed no errors.
Best wishes

Updated pubspec.yaml to newer resolvable versions

---

packages/pdfx/ios/Classes/Hooks.swift

UInt32 is deprecated on iOS 13.

[pdfx] fix: make it iOS 13 compatible

---

packages/pdfx/lib/src/renderer/has_pdf_support.dart
packages/pdfx/lib/src/renderer/interfaces/document.dart
packages/pdfx/lib/src/viewer/pinch/pdf_controller_pinch.dart
packages/pdfx/lib/src/viewer/pinch/pdf_view_pinch.dart
packages/pdfx/lib/src/viewer/simple/pdf_controller.dart
packages/pdfx/lib/src/viewer/simple/pdf_view.dart

We're currently not able to test pdfx viewer components in CI, as the viewer components assert that the current device has PDF support, and our CI is running linux. We've mocked out the pdf renderer, and we're supplying a MockPdfDocument to `PdfView`, which works fine on MacOS, but fails in CI. By moving the check to the renderer we can successfully test PdfView in CI.
I also removed `PdfViewState._currentIndex`. The main reason is because it was `late` inited, and removing the `await hasPdfSupport` check meant that it started being accessed before it was inited. It also had an off by one error on initialisation. Instead, we can just use the current value of the `pageListenable`.

Move pdf support check from viewer to renderer

---

packages/pdfx/lib/src/renderer/web/document/page.dart
packages/pdfx/lib/src/renderer/web/platform.dart

There were certain browser / system configurations that caused issues with pdf-rendering.
Those documents have lots of white patches / artifacts. This seems to only be observed in chrome based browers with Intel GPUs.
See:
https://github.com/wojtekmaj/react-pdf/issues/1010
https://github.com/wojtekmaj/react-pdf/issues/1025#issuecomment-1373922046

Fixup rendering issues in chromium based web-browsers.

---

packages/pdfx/lib/src/viewer/simple/pdf_controller.dart

Hi, I recently came across an error of which the stack trace is attached below
package name: pdfx
package version: 2.2.0
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [11:25:42]Null check operator used on a null value. Error thrown null.
at PdfController._loadDocument(pdf_controller.dart:125)
```
For solution, I purpose to remove the assert statement in the beginning of `_loadDocument()` since it is only executed in debug mode, and replace it with a normal null reference check.
flutter doctor result:
```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.5, on macOS 12.6 21G115 darwin-arm64, locale
en)
! Warning: `flutter` on your path resolves to
/Users/jiaqifung/Dev/flutter/bin/flutter, which is not inside your …
```

replace assert with return in `_loadDocument()`

---

packages/epub_view/lib/src/data/epub_cfi/_generator.dart

Fix this problem.
https://github.com/ScerIO/packages.flutter/issues/361
It seems there is a problem with the `_fileNameAsChapterName` method or the `getIdRefIndex` method is using the wrong condition.

[epub_view] Fix cfi generation

---

packages/pdfx/lib/src/viewer/pinch/pdf_view_pinch.dart

In the current version of PDFx, the PdfViewPinch widget provides a backgroundDecoration parameter. However, backgroundDecoration is not used anywhere. This pull request provides passing backgroundDecoration to _PdfViewPinchState and using it in the iterateLaidOutPages method to set page decoration.

[PDFx] Add ability to set page decoration

---

packages/pdfx/lib/src/renderer/web/document/document.dart

https://github.com/ScerIO/packages.flutter/issues/333
https://github.com/ScerIO/packages.flutter/issues/325#issuecomment-1188483275
Fixed "destroy" method not being called while closing a document

[pdfx] Memory leak (Web)

---

packages/pdfx/lib/src/viewer/simple/pdf_controller.dart

Thanks for the great library.
In my opinion, when a controller is attached to a view, the view state should be determined by the controller state.
In the current code, each time a controller is attached to a view, it is initialized with an initialPage.
This creates the problem that every time a controller on a page moved from initialPage is attached to a view, the page is initialized to initialPage.
This causes a problem in cases where the current controller is attached to another view, such as zooming in on an already open PDF overlay, which causes the page to revert from the currently open page to the initialPage.
Therefore, we modified the code so that when reInitController is executed, it initializes to the page held by the controller instead of initialPage.
[We are aware that …

[pdfx] avoid resetting to initialPage each view

---

packages/pdfx/pubspec.yaml

Updated the device info plus version since they did a major release. Not sure why they decided to do so, since the change itself is not that major.
Device info plus release notes here: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/CHANGELOG.md

chore: updated device_info_plus version

---

packages/pdfx/lib/src/renderer/has_pdf_support.dart
packages/pdfx/pubspec.yaml

The _plus packages are notorious for breaking version constraints. Having them as a transitive dependency in another library (for example pdfx) increases the risk of dependency hell.
Flutter itself only support Android API level 21 and newer (https://docs.flutter.dev/reference/supported-platforms).
So this check is never false.

feat: remove device_info_plus dependency

---

packages/pdfx/android/src/main/kotlin/io/scer/pdfx/Messages.kt
packages/pdfx/pubspec.yaml

Migrates SurfaceTexture to SurfaceProducer for Impeller android support. Resolves #521
Possibly TODO: 
- Support callback for redrawing producers if they are destroyed
https://docs.flutter.dev/release/breaking-changes/android-surface-plugins

[PDFX] Migrate to SurfaceProducer

---

packages/pdfx/README.md
packages/pdfx/lib/src/viewer/pinch/pdf_controller_pinch.dart
packages/pdfx/lib/src/viewer/pinch/pdf_view_pinch.dart

Motivation for "Document progress" feature: 
It will allow to observe percentage of reading and whether document scrolled to the end.

Implement document progress feature

---

packages/pdfx/lib/src/renderer/io/platform_method_channel.dart
packages/pdfx/lib/src/renderer/io/platform_pigeon.dart
packages/pdfx/lib/src/renderer/web/pdfjs.dart
packages/pdfx/lib/src/renderer/web/platform.dart
packages/pdfx/lib/src/viewer/base/pdf_page_number.dart
packages/pdfx/lib/src/viewer/interactive_viewer.dart
packages/pdfx/lib/src/viewer/pinch/pdf_view_pinch.dart
packages/pdfx/lib/src/viewer/simple/pdf_view.dart

**Description**:
This PR resolves the integration issues caused by the `use_super_parameters` and an unnecessary `library` declaration lint rules in `pdfx`.
* Refactored constructors in multiple files to use [super parameters](https://dart.dev/language/class-modifiers#super-parameters), improving code conciseness and compliance with the Dart style guide.
* Removed unnecessary `library` declaration from `lib/src/renderer/web/pdfjs.dart`.
* `lib/src/renderer/io/platform_method_channel.dart`
* `lib/src/renderer/io/platform_pigeon.dart`
* `lib/src/renderer/web/pdfjs.dart`
* `lib/src/renderer/web/platform.dart`
* `lib/src/viewer/base/pdf_page_number.dart`
* `lib/src/viewer/interactive_viewer.dart`
* `lib/src/viewer/pinch/pdf_view_pinch.dart`
* `lib/src/viewer/simple/pdf_view.dart`
* **18 …

Fixed CI resolving `dart analyze`
